<div class="">

	<div class="page-title">
		<div class="title_left">
			<h3>About</h3>
		</div>
	</div>

<div class="clearfix"></div>

<div class="row">

	<!-- Used software -->
	<div class="col-md-4 col-xs-12">
		<div class="x_panel">
		  <div class="x_title">
			<h2><i class="fa fa-html5"></i> Acknowledgements </h2>
			<div class="clearfix"></div>
		  </div>
		  <div class="x_content">
		  <h4>Design </h4>
			  <ul>
				  <li><a href="https://github.com/ColorlibHQ/gentelella">Gentelella Theme</a></li>
				  <li><a href="https://getbootstrap.com">Bootstrap</a></li>
				  <li><a href="https://fontawesome.com/v4.7.0/">Font Awesome</a></li>
					<li><a href="https://iconscout.com/contributors/iconscout">Favicon</a></li>
			  </ul>
			  
			<h4>Javascript Libaries </h4>
				<ul>
					<li><a href="https://jquery.com">jQuery</a></li>
					<li><a href="https://chartjs.org">Charts.js</a></li>
					<li><a href="https://datatables.net">dataTables</a></li>
					<li><a href="https://jvectormap.com">jVectorMap</a></li>
					<li><a href="https://abpetkov.github.io/switchery/">Switchery</a></li>
					<li><a href="https://chartjs.org">Charts.js</a></li>	
					<li><a href="https://github.com/davidstutz/bootstrap-multiselect">Bootstrap Multiselect</a></li>					 
				</ul> 
				
			  <h4>PHP Libaries </h4>
				<ul>
					<li><a href="https://github.com/aceat64/EasyBitcoin-PHP">EasyBitcoin-PHP</a></li>					   
				</ul> 
			
		  </div>
		</div>
	</div>
	<!-- End used software -->
	
	<!-- More information -->
	<div class="col-md-4 col-xs-12">
		<div class="x_panel">
		  <div class="x_title">
			<h2><i class="fa fa-info-circle"></i> More Information</h2>
			<div class="clearfix"></div>
		  </div>
		  <div class="x_content">
			<a href="https://github.com/Mirobit/bitcoin-node-manager/"><i class="fa fa-github-alt fa-4x github-hover col-md-2 col-xs-3"></i></a>
      <a href="https://www.reddit.com/r/Bitcoin/comments/kcehpy/i_build_a_lightweight_dashboard_for_your_bitcoin/"><i class="fa fa-reddit-alien fa-4x github-hover col-md-2 col-xs-3"></i></a>
		  </div>
		</div>
	</div>
	<!-- End More information -->
  
</div>
<!-- End Row-->

</div>
</div>
<!-- /page content -->

<!-- footer content -->
<?php include('views/footer.phtml') ?>
<!-- /footer content -->

</div>
</div>



</body>
</html>
