<div class="">

	<div class="page-title">
		<div class="title_left">
			<h3>About</h3>
		</div>
	</div>

<div class="clearfix"></div>

<div class="row">

	<!-- Used software -->
	<div class="col-md-4 col-xs-12">
		<div class="x_panel">
		  <div class="x_title">
			<h2><i class="fa fa-html5"></i> Used software <small></small></h2>
			<ul class="nav navbar-right panel_toolbox">
			  <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
			  </li>
			  <li><a class="close-link"><i class="fa fa-close"></i></a>
			  </li>
			</ul>
			<div class="clearfix"></div>
		  </div>
		  <div class="x_content">
		  <h4>Template </h4>
			  <ul>
				  <li><a href="https://colorlib.com">Gentelella Theme</a></li>
				  <li><a href="https://getbootstrap.com">Bootstrap</a></li>
				  <li><a href="https://fontawesome.io">Font Awesome</a></li>
			  </ul>
			  
			<h4>Javascript Libaries </h4>
				<ul>
					<li><a href="https://jquery.com">jQuery</a></li>
					<li><a href="https://chartjs.org">Charts.js</a></li>
					<li><a href="https://datatables.net">dataTables</a></li>
					<li><a href="https://jvectormap.com">jVectorMap</a></li>
					<li><a href="https://abpetkov.github.io/switchery/">Switchery</a></li>
					<li><a href="https://chartjs.org">Charts.js</a></li>	
					<li><a href="https://github.com/davidstutz/bootstrap-multiselect">Bootstrap Multiselect</a></li>					 
				</ul> 
				
			  <h4>PHP Libaries </h4>
				<ul>
					<li><a href="mailto:sergio@inservibile.org">JSON-RPC PHP</a></li>					   
				</ul> 
			
		  </div>
		</div>
	</div>
	<!-- End used software -->
	
	<!-- More information -->
	<div class="col-md-4 col-xs-12">
		<div class="x_panel">
		  <div class="x_title">
			<h2><i class="fa fa-info-circle"></i> More Information</h2>
			<ul class="nav navbar-right panel_toolbox">
			  <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
			  </li>
			  <li><a class="close-link"><i class="fa fa-close"></i></a>
			  </li>
			</ul>
			<div class="clearfix"></div>
		  </div>
		  <div class="x_content">

			<a href="https://github.com/Mirobit/bitcoin-node-manager/"><i class="fa fa-github-alt fa-4x github-hover col-md-2 col-xs-3"></i></a>
		  </div>
		</div>
	</div>
	<!-- End More information -->
  
</div>
<!-- End Row-->

</div>
</div>
<!-- /page content -->

<!-- footer content -->
<?php include('views/footer.phtml') ?>
<!-- /footer content -->

</div>
</div>

<!-- jQuery -->
<script src="vendors/jquery/dist/jquery.min.js"></script>
<!-- Bootstrap -->
<script src="vendors/bootstrap/dist/assets/js/bootstrap.min.js"></script>
<!-- FastClick -->
<script src="vendors/fastclick/lib/fastclick.js"></script>
<!-- NProgress -->
<script src="vendors/nprogress/nprogress.js"></script>
<!-- iCheck -->
<script src="vendors/iCheck/icheck.min.js"></script>
<!-- bootstrap-daterangepicker -->
<script src="vendors/moment/min/moment.min.js"></script>
<script src="vendors/jquery.hotkeys/jquery.hotkeys.js"></script>
<script src="vendors/google-code-prettify/src/prettify.js"></script>
<!-- Switchery -->
<script src="vendors/switchery/dist/switchery.min.js"></script>


<!-- Custom Theme Scripts -->
<script src="assets/js/custom.min.js"></script>


</body>
</html>
