		  <!-- Top Info Bar -->
		 <div class="panel panel-default">  
			<div class="panel-body">
				<div class="row tile_count">
					<div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
					  <span class="count_top"><i class="fa fa-cubes"></i> Total Blocks</span>
					  <div class="count"><?= $content["numberOfBlocks"] ?></div>
					  <span class="count_bottom"><span><?= $content["timeframe"] ?> </span> h timeframe</span>
					</div>
					<div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
					  <span class="count_top"><i class="fa fa-cloud-download" style="color:lightgreen;"></i> Latest Block</span>
					  <div class="count"><?= array_key_first($content["blocks"]) ?></div>
					  <span class="count_bottom"><span style="color:lightgreen;"><?= reset($content["blocks"])["timeago"] ?></span> min ago</span>
					</div>
					<div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
					  <span class="count_top"><i class="fa fa-database"></i> Size</span>
					  <div class="count"><?= $content["totalSize"] ?> <small>MB</small></div>
					  <span class="count_bottom"><span><?= $content["avgSize"] ?> </span> MB avg. block size</span>
					</div>
					<div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
					  <span class="count_top"><i class="fa fa-btc" style="color:orange;"></i> Total Fees</span>
					  <div class="count"><?= $content["totalFees"] ?> <small>BTC</small></div>
					  <span class="count_bottom"><span class="orange" ><?= $content["avgFee"] ?></span> avg. fees per block</span>
					</div>
					<div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
					  <span class="count_top"><i class="fa fa-line-chart" style="color:lightblue;"></i> Transactions</span>
					  <div class="count"><?= number_format($content["totalTx"]) ?></div>
					  <span class="count_bottom"><span style="color:lightblue;" ><?= $content["avgTxSize"] ?></span> KB avg. TX size</span>
					</div>
				  </div>
				  </div>
			 </div>
			<!-- Top Info Bar End-->
      <!-- Message -->
      <?php if(!empty($message)){ ?>
      <div class="row">
        <div class="col-md-3 col-sm-3 col-xs-12">
          <div class="alert alert-success" role="alert"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <?= $message ?>
          </div>
        </div>
      </div>
      <?php } ?>
      <!-- Message End -->
			<!-- Content -->				   
			<div class="row">
			
			<!-- Peer List -->
			  <div class="col-md-12 col-sm-12 col-xs-12">
				<div class="x_panel">
				  <div class="x_title">
					<h2>Blocks <small>Received</small></h2>
					<ul class="nav navbar-right panel_toolbox">
					  <li><a class="close-link"><i class="fa fa-close"></i></a>
					  <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
					  </li>
					  </li>
					</ul>
					<div class="clearfix"></div>
				  </div>
				  <div class="x_content">

					<table id="receivedblocks" class="table table-striped table-bordered table-valign">
					  <thead>
						<tr>
						  <th>ID</th>
						  <th>Hash</th>
						  <th>Time</th>
						  <th>Size <span style="font-weight:normal;">(MB)</span></th>
						  <th>Fees <span style="font-weight:normal;">(₿)</span></th>
						  <th>TXs</th>
						  <th>Voting</th>
						  <th style="min-width:60px;">Info</th>
						</tr>
					  </thead>


					  <tbody>
						<?php $i = 0;
							  foreach($content['blocks']  as $key => $block){ ?>
									<tr>
										<td><?= $key ?></td>
										<td><?php if($block['asicboost']){ ?><i class="fa fa-tachometer" title="Miner uses overt AsicBoost"></i><?php } else{ ?><span style="padding-left:18px;"></span><?php } ?> <?= $block["hash"] ?></td>  
										<td><?= $block["time"] ?> <small>(<?= $block["timeago"] ?> m ago)</small></td>  
										<td><?= $block["size"] ?></td>
										<td><?= $block["fees"] ?></td>  	
										<td><?= number_format($block["txcount"]) ?></td>
										<td><?php
										if(!empty($block['voting'])){
											foreach($block['voting'] as $key => $vote){
												echo '<button type="button" class="btn btn-default btn-xs">'.$key.'</button>';
											}	
										} ?>
										</td>										
										<td>																					  
										   
											<div class="btn-group pull-left" style="padding:5px 0 3px 7px; margin-bottom:0px">
												<button type="button" class="btn btn-default btn-xs">Details</button>
												<button type="button" class="btn btn-default dropdown-toggle btn-xs" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
													<span class="caret"></span>
													<span class="sr-only">Toggle Dropdown</span>
											  </button>
                        <ul class="dropdown-menu">
                          <li><a href="https://www.blockchain.com/btc/block/<?= $block["hash"] ?>" target="_blank"><i class="fa fa-globe fa-lg" style="color:lightblue"></i> Blockchain.com</a></li>
                          <li><a href="https://live.blockcypher.com/btc/block/<?= $block["hash"] ?>" target="_blank"><i class="fa fa-globe fa-lg" style="color:lightblue"></i> BlockCypher</a></li>
                          <li><a href="https://blockchair.com/bitcoin/block/<?= $block["hash"] ?>" target="_blank"><i class="fa fa-globe fa-lg" style="color:lightblue"></i> Blockchair</a></li>
                        </ul>
											</div>										   
								   </td>										   
								  </tr>

									  
						<?php } ?>						
					  </tbody>
					</table>
				  </div>
				  <div class="clearfix"></div>
				</div>
			  </div>
		  </div>
		</div>
	  </div>
	</div>
	<!-- /page content -->

	<!-- footer content -->
	<?php include('views/footer.phtml') ?>
	<!-- /footer content -->
	</div>
	</div>

	<!-- jQuery -->
	<script src="assets/js/jquery.min.js"></script>
	<!-- Bootstrap -->
	<script src="assets/js/bootstrap.min.js"></script>
	<!-- Datatables -->
	<script src="assets/js/jquery.dataTables.min.js"></script>
	<script src="assets/js/dataTables.bootstrap.min.js"></script>

	<!-- Custom Theme Scripts -->
	<script src="assets/js/custom.min.js"></script>

	<!-- Datatables -->
	<script>
	  $(document).ready(function() {
		
		 $('#receivedblocks').DataTable( {
			"order": [[ 0, "desc" ]],
			"paging":   false,
			"bInfo": false
		} );
		
	  });
	</script>
	<!-- /Datatables -->
  </body>
</html>