<footer>
<div class="pull-right">
<i class="fa fa-bitcoin orange"></i> <a href="https://github.com/mirobit/bitcoin-node-manager"> Node Manger v0.3.0</a> - © 2019
</div>
<div class="clearfix"></div>
</footer>
<script type="text/javascript">
	<?php
	if($this->section === "main"){
		$section = "";
	}else{
		$section = "?p=".$this->section;
	}
	?>
	window.history.pushState("", "", "<?= $section ?>");
</script>