		  <!-- Top Info Bar -->
		 <div class="panel panel-default">  
			<div class="panel-body">
				<div class="row tile_count">
					<div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
					  <span class="count_top"><i class="fa fa-code-fork"></i> Shown Forks</span>
					  <div class="count"><?= $content["forkCount"] ?></div>
					  <span class="count_bottom"><span>in last <?= $content["timeframe"] ?> days</span></span>
					</div>
					<div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
					  <span class="count_top"><i class="fa fa-code-fork"></i> Forks</span>
					  <div class="count"><?= $content["recentForks"] ?> </div>
					  <span class="count_bottom"><span>in last 24 hours</span>
					</div>
					<div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
					  <span class="count_top"><i class="fa fa-code-fork" style="color:orange;"></i> Last Fork</span>
					  <div class="count"><?= $content["blocks"][1]['height'] ?></div>
					  <span class="count_bottom"><span><?= $content["blocks"][1]['timeago'] ?></span><?php if(!empty($content["blocks"][1]['timeago'])) echo " days ago" ?></span>
					</div>
					<div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
					  <span class="count_top"><i class="fa fa-code-fork" style="color:lightgreen;"></i> Last Block Main Chain</span>
					  <div class="count"><?= $content["blocks"][0]['height'] ?></div>
					  <span class="count_bottom"><span><?= $content["blocks"][0]['timeago'] ?></span> min ago</span>
					</div>
				  </div>
				  </div>
			 </div>
			<!-- Top Info Bar End-->
      <!-- Message -->
      <?php if(!empty($message)){ ?>
      <div class="row">
        <div class="col-md-3 col-sm-3 col-xs-12">
          <div class="alert alert-success" role="alert"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <?= $message ?>
          </div>
        </div>
      </div>
      <?php } ?>
      <!-- Message End -->
			<!-- Content -->				   
			<div class="row">
			<!-- Peer List -->
			  <div class="col-md-12 col-sm-12 col-xs-12">
				<div class="x_panel">
				  <div class="x_title">
					<h2>Forks <small>Alternative chains / Orphaned blocks</small></h2>
					<ul class="nav navbar-right panel_toolbox">
					  <li><a class="close-link"><i class="fa fa-close"></i></a>
					  <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
					  </li>
					  </li>
					</ul>
					<div class="clearfix"></div>
				  </div>
				  <div class="x_content">

					<table id="orhpanedblocks" class="table table-striped table-bordered table-valign">
					  <thead>
						<tr>
						  <th>ID</th>
						  <th style="max-width: 500px;">Hash</th>
						  <th>Status</th>
						  <th>Time</th>
						  <th>Length</th>
						  <th>Size <span style="font-weight:normal;">(MB)</span></th>
						  <th>Voting</th>
						  <th style="min-width:60px;">Info</th>
					  </thead>
						</tr>

					  <tbody>
						<?php
							reset($content['blocks']);
							array_shift($content['blocks']);
							foreach($content['blocks'] as $block){ ?>
								<tr>
									<td><?= $block['height'] ?></td>
									<td><?= $block["hash"] ?></td>   
									<td><?= $block["status"] ?></td>
									<td><?= (isset($block["time"])) ? $block["time"]." <small>(".$block["timeago"]." days ago)</small>"  : "" ?></td>
									<td><?= $block['forklength'] ?></td>
									<td><?= (isset($block["size"])) ? $block["size"] : "" ?></td>	
									<td><?php
									if(!empty($block['voting'])){
										foreach($block['voting'] as $key => $vote){
											echo '<button type="button" class="btn btn-default btn-xs">'.$key.'</button>';
										}	
									} ?>
									</td>										
									<td>																						
										<div class="btn-group pull-left" style="padding:5px 0 3px 7px; margin-bottom:0px">
											<button type="button" class="btn btn-default btn-xs">Details</button>
											<button type="button" class="btn btn-default dropdown-toggle btn-xs" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
												<span class="caret"></span>
												<span class="sr-only">Toggle Dropdown</span>
										</button>
										<ul class="dropdown-menu">
										  <li><a href="https://bitcoin.jonasschnelli.ch/explorer/block/<?= $block["hash"] ?>" target="_blank"><i class="fa fa-globe fa-lg" style="color:lightblue"></i> Dumb Block Explorer</a></li>
											<li><a href="https://blockchair.com/search?q=<?= $block["hash"] ?>" target="_blank"><i class="fa fa-globe fa-lg" style="color:lightblue"></i> Blockchair</a></li>
										</ul>
										</div>										   
									</td>										   
								</tr>
						<?php } ?>						
					  </tbody>
					</table>
				  </div>
				  <div class="clearfix"></div>
				</div>
			  </div>
		  </div>
		</div>
	  </div>
	</div>
	<!-- /page content -->

	<!-- footer content -->
	<?php include('views/footer.phtml') ?>
	<!-- /footer content -->
	</div>
	</div>

	<!-- jQuery -->
	<script src="assets/js/jquery.min.js"></script>
	<!-- Bootstrap -->
	<script src="assets/js/bootstrap.min.js"></script>
	<!-- Datatables -->
	<script src="assets/js/jquery.dataTables.min.js"></script>
	<script src="assets/js/dataTables.bootstrap.min.js"></script>

	<!-- Custom Theme Scripts -->
	<script src="assets/js/custom.min.js"></script>

	<!-- Datatables -->
	<script>
	  $(document).ready(function() {
		
		 $('#orhpanedblocks').DataTable( {
			"order": [[ 0, "desc" ]],
			"paging":   false,
			"bInfo": false
		} );
		
	  });
	</script>
	<!-- /Datatables -->
  </body>
</html>