	  <!-- Top Info Bar -->
	<div class="panel panel-default">
		<div class="panel-body">
			<div class="row tile_count">
				<div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
					<span class="count_top"><i class="fa fa-database"></i> TX in Mempool</span>
					<div class="count"><?= number_format($content['node']->mempoolTx) ?></div>
					<span class="count_bottom"><i class="<?= $content['node']->mempoolUsageP['color'] ?>"><i class="fa <?= $content['node']->mempoolUsageP['icon'] ?>"></i> <?= $content['node']->mempoolUsageP['value'] ?>%</i> Usage</span>
				</div>
				<div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
					<span class="count_top"><i class="fa <?= $content['node']->mempoolUsageP['icon'] ?>"></i> Usage</span>
					<div class="count"><?= $content['node']->mempoolUsage ?> MB</div>
					<span class="count_bottom">of max. <?= $content['node']->maxMempool ?> MB</span>
				</div>
			</div>
		</div>
	</div>
	<!-- Top Info Bar End-->
  <!-- Message -->
  <?php if(!empty($message)){ ?>
  <div class="row">
    <div class="col-md-3 col-sm-3 col-xs-12">
      <div class="alert alert-success" role="alert"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <?= $message ?>
      </div>
    </div>
  </div>
  <?php } ?>
  <!-- Message End -->
			<!-- Content -->
			<div class="row">

			<!-- Peer List -->
			  <div class="col-md-12 col-sm-12 col-xs-12">
				<div class="x_panel">
				  <div class="x_title">
					<h2>Memory Pool <small>Transactions</small></h2>
					<ul class="nav navbar-right panel_toolbox">
					  <li><a class="close-link"><i class="fa fa-close"></i></a>
					  <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
					  </li>
					  </li>
					</ul>
					<div class="clearfix"></div>
				  </div>
				  <div class="x_content">
          The list of memory pool transactions was removed since the memory pool was getting too large for default php configurations
				  </div>
				  <div class="clearfix"></div>
				</div>
			  </div>
		  </div>
		</div>
	  </div>
	</div>
	<!-- /page content -->

	<!-- footer content -->
	<?php include('views/footer.phtml') ?>
	<!-- /footer content -->
	</div>
	</div>

	<!-- jQuery -->
	<script src="assets/js/jquery.min.js"></script>
	<!-- Bootstrap -->
	<script src="assets/js/bootstrap.min.js"></script>
	<!-- Datatables -->
	<script src="assets/js/jquery.dataTables.min.js"></script>
	<script src="assets/js/dataTables.bootstrap.min.js"></script>
	<script src="assets/js/dataTables.buttons.min.js"></script>

	<!-- Custom Theme Scripts -->
	<script src="assets/js/custom.min.js"></script>

	<!-- Datatables -->
	<script>
	  $(document).ready(function() {

		 $('#txmempool').DataTable( {
			"paging":   false,
			"bInfo": false,
			"order": [],
			"bFilter": false
		} );

	  });
	</script>
	<!-- /Datatables -->
  </body>
</html>
