	<!-- Top Info Bar -->
	<div class="panel panel-default">  
		<div class="panel-body">
			<div class="row tile_count">
				<div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
					<span class="count_top"><i class="fa fa-money"></i> Balance</span>
					<div class="count"><?= number_format($content['wallet']["balance"],8) ?></div>
				</div>
            <div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
					<span class="count_top"><i class="fa fa-money"></i> Watch-Only Balance</span>
					<div class="count"><?= number_format($content['wallet']["watchonly"],8) ?></div>
				</div>
				<div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
					<span class="count_top"><i class="fa fa-long-arrow-right"></i> Unconfirmed Balance</span>
					<div class="count"><?= number_format($content['wallet']["unconfirmed_balance"],8) ?></div>
				</div>
				<div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
					<span class="count_top"><i class="fa fa-clock-o"></i> Immature Balance</span>
					<div class="count"><?= number_format($content['wallet']["immature_balance"],8) ?></div>
				</div>
				<div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
					<span class="count_top"><i class="fa fa-address-card-o"></i> Wallet Version</span>
					<div class="count"><?= $content['wallet']["walletversion"] ?></div>
				</div>
				<div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
					<span class="count_top"><i class="fa fa-database"></i> TXCount</span>
					<div class="count"><?= $content['wallet']["txcount"] ?></div>
				</div>
			</div>
		</div>
	</div>
	<!-- Top Info Bar End-->
  <!-- Message -->
  <?php if(!empty($message)){ ?>
  <div class="row">
    <div class="col-md-3 col-sm-3 col-xs-12">
      <div class="alert alert-success" role="alert"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <?= $message ?>
      </div>
    </div>
  </div>
  <?php } ?>
  <!-- Message End -->
			<!-- Content -->				   
			<div class="row">
			
			<!-- Peer List -->
			  <div class="col-md-12 col-sm-12 col-xs-12">
				<div class="x_panel">
				  <div class="x_title">
					<h2>Wallet <small>Unspent Transactions</small></h2>
					<ul class="nav navbar-right panel_toolbox">
					  <li><a class="close-link"><i class="fa fa-close"></i></a>
					  <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
					  </li>
					  </li>
					</ul>
					<div class="clearfix"></div>
				  </div>
				  <div class="x_content">
					<table id="txmempool" class="table table-striped table-bordered table-valign">
					  <thead>
						<tr>
						  <th>ID</th>
						  <th>Amount</th>
						  <th>Address</th>
						  <th>TXID</th>
						  <th>Vout</th>
						  <th>Label</th>
						  <th>Confs</th>
						  <th>Info</th>

						</tr>
					  </thead>
					  <tbody>
						<?php $i = 0;
						if(isset($content["utxo"])) {
							  foreach($content["utxo"] as $key => $utxo){ ?>
									<tr>
										<td><?= $key+1 ?></td>
										<td><small><?= number_format($utxo["amount"],8) ?></small></td>
										<td><small><?= $utxo["address"] ?></small></td>  
										<td><small><?= $utxo["hash"] ?></small></td>  
										<td><small><?= $utxo["vout"] ?></small></td>  
										<td><small><?= $utxo["label"] ?></small></td>
										<td><small><?= $utxo["confs"] ?></small></td>  	
										<td> 
											<div class="btn-group pull-left" style="padding:5px 0 3px 7px; margin-bottom:0px">
												<button type="button" class="btn btn-default btn-xs">Details</button>
												<button type="button" class="btn btn-default dropdown-toggle btn-xs" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
													<span class="caret"></span>
													<span class="sr-only">Toggle Dropdown</span>
												</button>
												<ul class="dropdown-menu">
												<li><a href="https://www.blockchain.com/btc/tx/<?= $utxo["hash"] ?>" target="_blank"><i class="fa fa-globe fa-lg" style="color:lightblue"></i> Blockchain.com</a></li>
												<li><a href="https://live.blockcypher.com/btc/tx/<?= $utxo["hash"] ?>" target="_blank"><i class="fa fa-globe fa-lg" style="color:lightblue"></i> BlockCypher</a></li>
												</ul>
											</div>										   
										</td> 
									</tr>
						<?php } } ?>						
					  </tbody>
					</table>
				  </div>
				  <div class="clearfix"></div>
				</div>
			  </div>
		  </div>
		</div>
	  </div>
	</div>
	<!-- /page content -->

	<!-- footer content -->
	<?php include('views/footer.phtml') ?>
	<!-- /footer content -->
	</div>
	</div>

	<!-- jQuery -->
	<script src="assets/js/jquery.min.js"></script>
	<!-- Bootstrap -->
	<script src="assets/js/bootstrap.min.js"></script>
	<!-- Datatables -->
	<script src="assets/js/jquery.dataTables.min.js"></script>
	<script src="assets/js/dataTables.bootstrap.min.js"></script>
	<script src="assets/js/dataTables.buttons.min.js"></script>
	<!-- Custom Theme Scripts -->
	<script src="assets/js/custom.min.js"></script>
  
	<!-- Custom Datatables Script -->
	<script src="assets/js/custom/datatables-wallet.js"></script>
	<!-- /Datatables -->
  </body>
</html>