	  <!-- Top Info Bar -->
	<div class="panel panel-default">  
		<div class="panel-body">
			<div class="row tile_count">
				<div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
					<span class="count_top"><i class="fa fa-money"></i> Balance</span>
					<div class="count"><?= number_format($content['node']->walBal,8) ?></div>
				</div>
				<div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
					<span class="count_top"><i class="fa fa-plane"></i> Unconfirmed Balance</span>
					<div class="count"><?= number_format($content['node']->waluBal,8) ?></div>
				</div>
				<div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
					<span class="count_top"><i class="fa fa-clock-o"></i> Immature Balance</span>
					<div class="count"><?= number_format($content['node']->waliBal,8) ?></div>
				</div>
				<div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
					<span class="count_top"><i class="fa fa-database"></i> Wallet Version</span>
					<div class="count"><?= $content['node']->walVer ?></div>
				</div>
				<div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
					<span class="count_top"><i class="fa fa-database"></i> TXCount</span>
					<div class="count"><?= $content['node']->walTxcount ?></div>
				</div>
			</div>
		</div>
	</div>
	<!-- Top Info Bar End-->
	<div class="clearfix"></div>
	<?php if(!empty($error) OR !empty($message)){ ?>
	<div class="col-md-3 col-sm-3 col-xs-12">
		<?php if(!empty($error)){ ?> <div class="alert alert-danger" role="alert"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
		<?= $error ?> </div><?php }
		 if(!empty($message)){ ?> <div class="alert alert-success" role="alert"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
		<?= $message ?> </div><?php } ?>
	</div>  
	<?php } ?>
			<!-- Content -->				   
			<div class="row">
			
			<!-- Peer List -->
			  <div class="col-md-12 col-sm-12 col-xs-12">
				<div class="x_panel">
				  <div class="x_title">
					<h2>Transactions <small>Memory Pool</small></h2>
					<ul class="nav navbar-right panel_toolbox">
					  <li><a class="close-link"><i class="fa fa-close"></i></a>
					  <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
					  </li>
					  </li>
					</ul>
					<div class="clearfix"></div>
				  </div>
				  <div class="x_content">
					<table id="txmempool" class="table table-striped table-bordered table-valign">
					  <thead>
						<tr>
						  <th>ID</th>
						  <th>Amount</th>
						  <th>Address</th>
						  <th>TXID</th>
						  <th>Vout</th>
						  <th>Account</th>
						  <th>scriptPubKey</th>
						  <th>Confs</th>
						  <th>Sendable</th>
						  <th>Solvable</th>
						  <th>Safe</th>
						  <th>Info</th>

						</tr>
					  </thead>
					  <tbody>
						<?php $i = 0;
							  foreach($content['utxo'] as $key => $utxo){ ?>
									<tr>
										<td><small><?= number_format($utxo["amount"],8) ?></small></td>
										<td><small><?= $utxo["address"] ?></small></td>  
										<td><small><?= $utxo["hash"] ?></small></td>  
										<td><small><?= $utxo["vout"] ?></small></td>  
										<td><small><?= $utxo["account"] ?></small></td>
										<td><small><?= $utxo["scriptpubkey"] ?></small></td>  	
										<td><small><?= $utxo["confs"] ?></small></td>  	
										<td><small><?= $utxo["spendable"] ?></small></td>  	
										<td><small><?= $utxo["solvable"] ?></small></td>  	
										<td><small><?= $utxo["safe"] ?></small></td>
										<td> 
											<div class="btn-group pull-left" style="padding:5px 0 3px 7px; margin-bottom:0px">
												<button type="button" class="btn btn-default btn-xs">Details</button>
												<button type="button" class="btn btn-default dropdown-toggle btn-xs" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
													<span class="caret"></span>
													<span class="sr-only">Toggle Dropdown</span>
												</button>
												<ul class="dropdown-menu">
												<li><a href="https://blockchain.com/btc/tx/<?= $utxo["hash"] ?>" target="_blank"><i class="fa fa-globe fa-lg" style="color:lightblue"></i> Blockchain.com</a></li>
												<li><a href="https://live.blockcypher.com/btc/tx/<?= $utxo["hash"] ?>" target="_blank"><i class="fa fa-globe fa-lg" style="color:lightblue"></i> BlockCypher</a></li>
												<li><a href="https://www.smartbit.com.au/tx/<?= $utxo["hash"] ?>" target="_blank"><i class="fa fa-globe fa-lg" style="color:lightblue"></i> Smartbit</a></li>
												</ul>
											</div>										   
										</td> 
									</tr>
						<?php } ?>						
					  </tbody>
					</table>
				  </div>
				  <div class="clearfix"></div>
				</div>
			  </div>
		  </div>
		</div>
	  </div>
	</div>
	<!-- /page content -->

	<!-- footer content -->
	<?php include('views/footer.phtml') ?>
	<!-- /footer content -->
	</div>
	</div>

	<!-- jQuery -->
	<script src="assets/js/jquery.min.js"></script>
	<!-- Bootstrap -->
	<script src="assets/js/bootstrap.min.js"></script>
	<!-- Datatables -->
	<script src="assets/js/jquery.dataTables.min.js"></script>
	<script src="assets/js/dataTables.bootstrap.min.js"></script>
	<script src="assets/js/dataTables.buttons.min.js"></script>
	<script src="assets/js/responsive.bootstrap.js"></script>

	<!-- Custom Theme Scripts -->
	<script src="assets/js/custom.min.js"></script>

	<!-- Datatables -->
	<script>
	  $(document).ready(function() {
		
		 $('#txmempool').DataTable( {
			"paging":   false,
			"bInfo": false,
			"order": [],
			"bFilter": false
		} );
		
	  });
	</script>
	<!-- /Datatables -->
  </body>
</html>